apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: familycabin-storage-pvc
  namespace: familycabin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client