apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  namespace: familycabin-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-client