apiVersion: v1
kind: Secret
metadata:
  name: familycabin-secrets
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  MONGODB_ROOT_PASSWORD: "${MONGODB_ROOT_PASSWORD}"
  MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
  JWT_SECRET: "$(openssl rand -base64 32)"
  GOOGLE_CLIENT_ID: "to-be-configured"
  GOOGLE_CLIENT_SECRET: "to-be-configured"
  FACEBOOK_APP_ID: "to-be-configured"
  FACEBOOK_APP_SECRET: "to-be-configured"
  APPLE_CLIENT_ID: "to-be-configured"
  APPLE_TEAM_ID: "to-be-configured"
  APPLE_KEY_ID: "to-be-configured"