apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: familycabin-api
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: familycabin-api
  namespaceSelector:
    matchNames:
      - ${NAMESPACE}
  endpoints:
  - port: metrics
    interval: 15s