# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslamate
  namespace: teslamate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teslamate
  template:
    metadata:
      labels:
        app: teslamate
    spec:
      containers:
        - name: teslamate
          image: teslamate/teslamate:latest
          ports:
            - containerPort: 4000
          env:
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: teslamate-encryption-key
                  key: ENCRYPTION_KEY
            - name: DATABASE_USER
              value: "teslamate"
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: teslamate-db-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_NAME
              value: "teslamate"
            - name: DATABASE_HOST
              value: "database.teslamate.svc.cluster.local"
            - name: MQTT_HOST
              value: "mosquitto.teslamate.svc.cluster.local"
          volumeMounts:
            - name: teslamate-import
              mountPath: /opt/app/import
          securityContext:
            capabilities:
              drop:
                - ALL
      volumes:
        - name: teslamate-import
          persistentVolumeClaim:
            claimName: teslamate-import-pvc
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: teslamate
  namespace: teslamate
spec:
  type: LoadBalancer
  selector:
    app: teslamate
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
