apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: zabbix-server
  replicas: 1
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      volumes:
      - name: zabbix-config
        persistentVolumeClaim:
          claimName: zabbix-server-pvc
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql:latest
        env:
        - name: DB_SERVER_HOST
          value: mysql
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: p@ssword12
        - name: MYSQL_DATABASE
          value: zabbix
        ports:
        - containerPort: 10051
          name: zabbix-port
        volumeMounts:
        - name: zabbix-config
          mountPath: /etc/zabbix            # For configuration files
        - name: zabbix-config
          mountPath: /usr/share/snmp/mibs   # For SNMP MIBs
          subPath: mibs                     # Assumes MIBs are in a subdirectory 'mibs' in the PVC
        - name: zabbix-config
          mountPath: /var/lib/zabbix        # For Zabbix data
          subPath: data                     # Assumes data is in a subdirectory 'data' in the PVC
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: monitoring
spec:
  ports:
    - port: 10051
      targetPort: 10051
  selector:
    app: zabbix-server
