# zabbix-web-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-web-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
