apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: zabbix-web
  replicas: 1
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      volumes:
      - name: zabbix-web-config
        persistentVolumeClaim:
          claimName: zabbix-web-pvc
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-mysql:latest
        env:
        - name: DB_SERVER_HOST
          value: mysql
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: p@ssword12
        - name: MYSQL_DATABASE
          value: zabbix
        - name: ZBX_SERVER_HOST
          value: zabbix-server
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        volumeMounts:
        - name: zabbix-web-config
          mountPath: /etc/zabbix/web          # For web configurations
        - name: zabbix-web-config
          mountPath: /var/log/nginx           # For logs
          subPath: logs                       # Assumes logs are stored in 'logs' directory in the PV
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 443
      targetPort: 8443
      name: https
  selector:
    app: zabbix-web
