apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-app
  namespace: monitoring
data:
  MYSQL_DATABASE: zabbix
  ZBX_SERVER_HOST: zabbix-server
  ZBX_HOSTNAME: zabbix-agent
  ZBX_SERVER_NAME: Zabbix Server
