apiVersion: v1
kind: Secret
metadata:
  name: zabbix-app
  namespace: monitoring
type: Opaque
data:
  MYSQL_USER: emFiYml4          # Base64 for 'zabbix'
  MYSQL_PASSWORD: emFiYml4      # Base64 for 'zabbix'
  MYSQL_ROOT_PASSWORD: cm9vdF9wd2Q=   # Base64 for 'root_pwd'
