apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-frontend
  namespace: monitoring
  labels:
    app: zabbix-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-frontend
  template:
    metadata:
      labels:
        app: zabbix-frontend
    spec:
      containers:
        - name: zabbix-frontend
          image: zabbix/zabbix-web-nginx-mysql:ubuntu-4.4-latest
          env:
            - name: DB_SERVER_HOST
              value: mysql-server
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: zabbix-app
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-app
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-app
                  key: MYSQL_PASSWORD
            - name: ZBX_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: zabbix-app
                  key: ZBX_SERVER_HOST
            - name: ZBX_SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  name: zabbix-app
                  key: ZBX_SERVER_NAME
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
# Service for Zabbix Frontend
apiVersion: v1
kind: Service
metadata:
  name: zabbix-frontend
  namespace: monitoring
  labels:
    app: zabbix-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: zabbix-frontend
