apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: monitoring
  labels:
    app: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql:ubuntu-4.4-latest
          env:
            - name: DB_SERVER_HOST
              value: mysql-server
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: zabbix-app
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-app
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-app
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 10051
          volumeMounts:
            - name: zabbix-server-config
              mountPath: /etc/zabbix/zabbix_server.conf
              subPath: zabbix_server.conf
      volumes:
        - name: zabbix-server-config
          configMap:
            name: zabbix-server-config
---
# Service for Zabbix Server
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: monitoring
  labels:
    app: zabbix-server
spec:
  ports:
    - port: 10051
      targetPort: 10051
  selector:
    app: zabbix-server
