apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 172.18.232.240/32
  - 172.18.232.241/32
  - 172.18.232.242/32
  - 172.18.232.243/32
  - 172.18.232.244/32
  - 172.18.232.245/32
  - 172.18.232.246/32
  - 172.18.232.247/32
  - 172.18.232.248/32
  - 172.18.232.249/32
  - 172.18.232.250/32
  - 172.18.232.251/32
  - 172.18.232.252/32
  - 172.18.232.253/32
  - 172.18.232.254/32
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
  - default
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: default
  namespace: metallb-system
spec:
  myASN: 64790
  peerASN: 64791
  peerAddress: 172.18.232.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
  - default