apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- home-assistant/
- mosquitto/
- metallb/
- nginx/

configMapGenerator:
- behavior: replace
  literals:
  - TZ="Europe/Budapest"
  name: home-assistant-config

patches:
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: ha.example.com
    - op: replace
      path: /spec/tls/0/secretName
      value: ha.example.com-production-secret
    - op: replace
      path: /spec/rules/0/host
      value: ha.example.com
  target:
    kind: Ingress
    name: home-assistant
    version: v1
- patch: |-
    - op: replace
      path: /spec/addresses/0
      value: 10.1.1.10/32
  target:
    kind: IPAddressPool
    name: iot
- patch: |-
    - op: replace
      path: /spec/addresses/0
      value: 192.168.1.10/32
  target:
    kind: IPAddressPool
    name: lan
- patch: |-
    - op: replace
      path: /spec/loadBalancerIP
      value: 10.1.1.10
  target:
    kind: Service
    name: ingress-nginx-controller