apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: familycabin
spec:
  serviceName: postgres-db-service  # Headless service for stable network identity
  replicas: 1                       # Single instance
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: postgres:14            # Specific version for stability
        env:
        - name: POSTGRES_DB
          value: familycabin          # Default database name
        - name: POSTGRES_USER
          value: cabinuser            # User name
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD  # Secret for the password
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-pvc